config/routes.rb
if ENV['RAILS_RELATIVE_URL_ROOT']
  Rails.application.routes.default_scope = ENV['RAILS_RELATIVE_URL_ROOT']
end

Rails.application.routes.draw do
  # ------------------------------------------------------------ Authentication
  # Sign in / sign out
  get '/login'  => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  resource :session

  resources :comments

  # ------------------------------------------------------------ Project routes
  concern :multiple_destroy do
    collection do
      delete :multiple_destroy
    end
  end

  resources :notifications, only: [:index, :update]

  resources :projects, only: [:index, :show] do
    resources :activities, only: [:index] do
      collection do
        get :poll, constraints: { format: /js/ }
      end
    end

    resources :boards do
      resources :lists, except: [:index] do
        member { post :move }
        resources :cards, except: [:index] do
          member { post :move }
          resources :revisions, only: [:index, :show]
        end
      end
    end

    constraints id: %r{[(0-z)\/]+} do
      resources :configurations, only: [:index, :update]
    end

    post :create_multiple_evidence, to: 'issues/evidence#create_multiple'

    resources :issues, concerns: :multiple_destroy do
      collection do
        post :import
        resources :merge, only: [:new, :create], controller: 'issues/merge'
      end

      resources :evidence, concerns: :multiple_destroy, controller: 'issues/evidence', only: [:index, :new]
      resources :nodes, only: [:show], controller: 'issues/nodes'
      resources :revisions, only: [:index, :show]
    end

    resources :methodologies do
      collection { post :preview }
      member do
        get :add
        put :update_task
      end
    end

    resources :nodes do
      collection do
        post :sort
        post :create_multiple
      end

      member do
        get :tree
      end

      resource :merge, only: [:create], controller: 'nodes/merge'

      resources :notes, concerns: :multiple_destroy do
        resources :revisions, only: [:index, :show]
      end

      resources :evidence, except: :index, concerns: :multiple_destroy do
        resources :revisions, only: [:index, :show]
      end

      constraints(filename: /.*/) do
        resources :attachments, param: :filename
      end
    end

    resources :notifications, only: [:index, :update]

    resources :revisions, only: [] do
      member { post :recover }
    end

    get 'search' => 'search#index'
    get 'trash' => 'revisions#trash'

    # ------------------------------------------------------- Export Manager
    get  '/export'                   => 'export#index',             as: :export_manager
    post '/export'                   => 'export#create'
    get  '/export/validate'          => 'export#validate',          as: :validate_export
    get  '/export/validation_status' => 'export#validation_status', as: :validation_status

    # ------------------------------------------------------- Upload Manager
    get  '/upload'        => 'upload#index',  as: :upload_manager
    post '/upload'        => 'upload#create'
    post '/upload/parse'  => 'upload#parse'

    if Rails.env.development?
      get '/styles'          => 'styles_tylium#index'
    end
  end

  resources :console, only: [] do
    collection { get :status }
  end

  resource :fields, only: [] do
    collection do
      get :field
      post :form
      post :source
    end
  end

  namespace :setup, only: [:index] do
    if defined?(Dradis::Pro)
    else
      resource :kit, only: [:new, :create]
      resource :password, only: [:new, :create]
    end
  end

  resources :subscriptions, only: [:index, :create, :destroy]

  # -------------------------------------------------------------- Static pages
  resource :markup, controller: :markup, only: [] do
    get :help
    post :preview
  end

  if defined?(Dradis::Pro)
  else
    root to: 'setup/passwords#new'
  end

  mount ActionCable.server => '/cable'
end

app/models/notification.rb
class Notification < ApplicationRecord
  # -- Relationships --------------------------------------------------------
  belongs_to :actor, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
  belongs_to :notifiable, polymorphic: true

  # -- Callbacks ------------------------------------------------------------

  # -- Validations ----------------------------------------------------------
  validates :action, presence: true
  validates :actor, presence: true, associated: true
  validates :notifiable, presence: true, associated: true
  validates :recipient, presence: true, associated: true

  # -- Scopes ---------------------------------------------------------------
  scope :newest,  -> { order(created_at: :desc) }
  scope :read,    -> { where.not(read_at: nil) }
  scope :unread,  -> { where(read_at: nil) }

  # All unread notifications within a given span of time
  scope :since, -> (time_ago = 1.day.ago) {
    where('created_at >= ?', time_ago).unread.newest
  }

  # -- Class Methods --------------------------------------------------------

  def self.mark_all_as_read!
    # update_all doesnt update timestamps, so do it manually to bust the cache:
    update_all(read_at: Time.now, updated_at: Time.now)
  end

  def self.for_digest(interval)
    NotificationGroup.new(since(interval).includes(notifiable: :commentable))
  end

  # -- Instance Methods -----------------------------------------------------
  def read?
    self.read_at
  end

  def read!(time = Time.now)
    return if self.read_at
    self.update_attribute :read_at, time
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < AuthenticatedController
  include ProjectScoped

  skip_before_action :set_project, if: -> { params[:project_id].blank? }
  skip_before_action :set_nodes, if: -> { params[:project_id].blank? }

  def index
    notifications = current_user.notifications.newest.includes(
      :actor, notifiable: [:user, :commentable]
    )
    respond_to do |format|
      format.html do
        @notifications = notifications.page(params[:page])
      end
      format.js do
        @project_id = params[:project_id]
        @notifications = notifications.limit(20)
        # NB the unread count is not the same as @notifications.count because
        # @notifications a) includes read notifs and b) is capped at 20
        @unread_count  = current_user.notifications.unread.count
      end
    end
  end

  def update
    @notifications =
      if params[:id] == 'all'
        current_user.notifications
      elsif params[:id]
        current_user.notifications.where(id: params[:id])
      end

    @updated_count = @notifications.unread.mark_all_as_read!

    @has_unread = current_user.notifications.unread.any?

    respond_to do |f|
      f.js do
        if @updated_count > 0
          @ids = @notifications.map(&:id)
        else
          head :ok
        end
      end

      f.html { redirect_to notifications_path }
    end
  end

  protected

  # ProjectScoped always call ProjectScoped#info_for_paper_trail with the current_project.
  # We have to overwrite it here so that it doesn't return an error.
  def info_for_paper_trail
    return if params[:project_id].blank?

    super
  end
end

app/views/notifications/_dropdown.html.erb
<% cache [current_user, notifications, project_id] do %>
   <% if notifications.any? %>
  <div class="notification-header">
    Notifications
    (<span data-behavior='unread-count'><%= unread_count %></span>)
    <div class="pull-right">
      <%= link_to 'Mark all as read',
                  notification_path(id: 'all'),
                  method: :put,
                  remote: true
                  %>
    </div>
  </div>
  <% end %>
  <ul class="notification-container" >
    <% if notifications.any? %>
      <%= render notifications %>
    <% else %>
      <li class="text-center">You don't have any notifications yet.</li>
    <% end %>
  </ul>
  <% if notifications.any? %>
    <div class="footer text-center">
      <%= link_to 'See all notifications', project_id ? project_notifications_path(project_id) : notifications_path %>
    </div>
  <% end %>
<% end %>

app/views/notifications/_header.html.erb
All Notifications
<% if @notifications.any? %>
  <b><%= link_to 'Mark all as read', notification_path(id: 'all'), class: 'actions pull-right', method: :put, remote: true %></b>
<% end %>

app/views/notifications/_notification.html.erb
<%# NB this template is rendered both in the notification navbar %>
<%# and on notifications#index                                   %>
<% present notification do |presenter| %>
  <li class="notification <%= notification.read? ? '' : 'unread' %>" data-notification-id="<%= notification.id %>">

    <div class="details">
      <%= presenter.avatar_with_link(40) %>
    </div>

    <div class="body">

      <div class="title">
        <%= presenter.render_title %>
      </div>

      <div class="time">
        <%= presenter.created_at_ago %>
      </div>

    </div>
    <%= presenter.icon %>

    <% if !notification.read? %>
      <%= link_to notification_path(notification),
                  title: 'Mark as read',
                  class: 'notification-read',
                  data: { behavior: 'notification-read' },
                  remote: true,
                  method: :put do %>
        <i class="fa fa-check-circle-o" aria-hidden="true"><span class="sr-only">Mark as read</span></i>
      <% end %>
    <% end %>
  </li>
<% end %>

app/views/notifications/_notifications.html.erb
<% cache [current_user, @notifications] do %>
  <% if @notifications.any? %>
    <div class="notifications-index">
      <ul class="p-0 m-0">
        <% @notifications.each do |notification| %>
          <%= render notification %>
        <% end %>
      </ul>
    </div>
    <%= paginate @notifications %>
  <% else %>
    <%= render 'shared/empty_state',
      name: 'notification',
      docs_link: 'https://dradisframework.com/support/guides/projects/comments.html#notify',
      text: 'Use the notifications feed to stay updated on conversations relevant to you.'
    %>
  <% end %>
<% end %>

app/views/notifications/index.html.erb
<% content_for :title, 'Notifications' %>

<% if @current_project %>
  <div class="content-container">
    <h4 class="header-underline w-100">
      <%= render partial: 'notifications/header' %>
    </h4>
    <%= render partial: 'notifications/notifications' %>
  </div>
<% else %>
  <div class="card">
    <div class="card-header bg-primary">
      <div class="card-title">
        <%= render partial: 'notifications/header' %>
      </div>
    </div>
    <%= render partial: 'notifications/notifications' %>
  </div>
<% end %>

app/views/notifications/index.js.erb
<% partial = escape_javascript(
  render partial: 'dropdown',
  locals: { notifications: @notifications,  unread_count: @unread_count, project_id: @project_id }
) %>
$('[data-behavior~=notifications-dropdown] + div').html("<%= partial %>");

$('[data-behavior~=notification-read]').on('ajax:beforeSend', function(event){
  // Don't send out ajax when reading a 'read' notification
  if(!$(this).parent().hasClass('unread')) return false;
});

app/views/notifications/update.js.erb
<% @ids.each do |id| %>
$notification = $('[data-notification-id="' + <%= id %> + '"]');
$notification.removeClass('unread');
$notification.find('[data-behavior~=notification-read]').remove();
<% end %>

$unreadCount  = $('[data-behavior~=unread-count]');
$unreadCount.text(parseInt($unreadCount.text()) - <%= @updated_count %>);

<% unless @has_unread %>
$('[data-behavior~=notifications-dot]').addClass('d-none');
<% end %>